name: Verify
on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn install
      - run: yarn download
      - run: yarn build
      - run: yarn lint
